# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
}

terraform {
  required_providers {
    aws = {
      source  = "registry.terraform.io/hashicorp/aws"
      version = "3.63.0"
    }
  }
  required_version = ">=1.0.7"
}

locals {
  region  = "us-east-1"
  project = "wp-blog"
  env     = "dev"
}

module "vpc" {
  source = "./vpc/"

  # vpc
  cidr_block       = "10.0.0.0/16"
  public_subnets   = ["10.0.1.0/24", "10.0.2.0/24"]
  private_subnets  = ["10.0.11.0/24", "10.0.12.0/24"]
  database_subnets = ["10.0.21.0/24", "10.0.22.0/24"]

  region  = local.region
  project = local.project
  env     = local.env  

  tags = {
    Project     = local.project
    Environment = local.env
  } 
}

module "alb" {
  source = "./alb/"

  alb_port       = 80
  host_port      = 80

  vpc_id = module.vpc.vpc_id
  public_subnets = module.vpc.public_subnets

  project = local.project
  env     = local.env  

  tags = {
    Project     = local.project
    Environment = local.env
  } 
}

module "rds" {
  source = "./rds/"

  vpc_id              = module.vpc.vpc_id
  database_subnets    = module.vpc.database_subnets
  private_cidr_blocks = module.vpc.private_cidr_blocks
  public_cidr_blocks  = module.vpc.public_cidr_blocks

   project = local.project
  env     = local.env  

  tags = {
    Project     = local.project
    Environment = local.env
  }  
}

module "efs" {
  source = "./efs/"

  private_subnets = module.vpc.private_subnets
  vpc_id          = module.vpc.vpc_id

  project = local.project
  env     = local.env  

  tags = {
    Project     = local.project
    Environment = local.env
  }  
}


module "ecs" {
  source = "./ecs/"

  task_cpu    = 512
  task_memory = 1024
  container_port = 80
  alb_port       = 80
  host_port      = 80

  vpc_id              = module.vpc.vpc_id
  private_subnets     = module.vpc.private_subnets
  private_cidr_blocks = module.vpc.private_cidr_blocks
  public_subnets      = module.vpc.public_subnets
  public_cidr_blocks  = module.vpc.public_cidr_blocks

  # efs
  efs_id               = module.efs.efs_id
  efs_arn              = module.efs.efs_arn
  efs_access_point_arn = module.efs.efs_access_point_arn
  efs_access_point_id  = module.efs.efs_access_point_id

  # alb
  alb_dns_name               = module.alb.alb_dns_name
  alb_target_group_arns      = module.alb.alb_target_group_arns
  alb_target_group_names     = module.alb.alb_target_group_names
  alb_https_listener_arns    = module.alb.alb_https_listener_arns
  alb_http_tcp_listener_arns = module.alb.alb_http_tcp_listener_arns
  alb_sg                     = module.alb.alb_sg

  # rds
  db_secrets_arn = module.rds.db_secrets_arn
  
  project = local.project
  env     = local.env  
  region  = local.region

  tags = {
    Project     = local.project
    Environment = local.env
  }  
}
